# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  database: dream_car_development
  adapter: mysql2
  pool: 5
  timeout: 5000
  user: root
  password:
  host: 127.0.0.1
